ARG AWS_ACCOUNT_ID
ARG AWS_REGION

FROM --platform=linux/amd64 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/base-ws:alpine-3.22 AS base_ws_amd64

RUN npm install -g \
  @anthropic-ai/claude-code@latest \
  @executeautomation/playwright-mcp-server@1.0.1 @wonderwhy-er/desktop-commander@0.1.19 && \
  # Configure MCP server to use Playwright and Desktop-Commander
  $HOME/bin/claude mcp add playwright playwright-mcp-server && \
  $HOME/bin/claude mcp add desktop-commander desktop-commander && \
  # playwright-mcp-server
  cd $HOME/bin && cd $(dirname $(readlink playwright-mcp-server)) && \
  sudo sed -i 's/headless = false/headless = true/g' toolHandler.js

RUN curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | CONFIGURE=false bash