ARG AWS_ACCOUNT_ID
ARG AWS_REGION

FROM --platform=linux/amd64 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/base-ws:ubuntu-noble

ARG CLAUDE_CODE_VER=latest
ARG PLAYWRIGHT_VER=latest
ARG DESKTOP_COMMANDER_VER=latest
ARG HTTP_SERVER_VER=latest

RUN npm install -g \
  @anthropic-ai/claude-code@$CLAUDE_CODE_VER \
  @executeautomation/playwright-mcp-server@$PLAYWRIGHT_VER \
  @wonderwhy-er/desktop-commander@$DESKTOP_COMMANDER_VER \
  http-server@$HTTP_SERVER_VER && \
  # Configure MCP server to use Playwright and Desktop-Commander
  $HOME/bin/claude mcp add playwright playwright-mcp-server && \
  $HOME/bin/claude mcp add desktop-commander desktop-commander && \
  # playwright-mcp-server
  cd $HOME/bin && cd $(dirname $(readlink playwright-mcp-server)) && \
  sudo sed -i 's/headless = false/headless = true/g' toolHandler.js